name: Lint frontend

on:
  push:
    paths:
      - src/frontend/**
      - .github/workflows/lint-frontend.yml
  pull_request:
    paths:
      - src/frontend/**
      - .github/workflows/lint-frontend.yml

jobs:
  lint:
    name: Lint frontend
    runs-on: ubuntu-latest
    steps:
      - name: Run Shared Setup Steps
        uses: ./.github/workflows/setup
        with:
          setup-node: 'true'
      - run: echo "::add-matcher::.github/problem-matchers.json"
      - name: Install frontend dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile
      - name: Lint frontend
        working-directory: src/frontend
        run: pnpm run lint
      - name: Check frontend formatting
        working-directory: src/frontend
        run: pnpm run format:check
