name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run Shared Setup Steps
        uses: ./.github/workflows/setup
        with:
          setup-gradle: 'true'
          setup-node: 'true'
          setup-playwright: 'true'

      - name: Build with gradle
        run: ./gradlew build release apiCheck --scan -Pnpm.download=false

      - name: PR playwright - upload
        id: pr_playwright-upload
        if: github.event.pull_request.number != '' && hashFiles('./src/frontend/tests/playwright-report') != ''
        timeout-minutes: 1
        working-directory: ./src/frontend/tests/playwright-report/data
        env:
          # using live@icpc.global IMGBB acount
          IMGBB_API_TOKEN: ${{ secrets.IMGBB_API_TOKEN }}
        run: |
          ls *.png | \
            xargs -i curl -s -P1 --location --request POST "https://api.imgbb.com/1/upload?expiration=604800&key=$IMGBB_API_TOKEN" --form "image=@{}" | \
            jq -r '.data.image.url' | paste -sd "," - | awk '{print "pr_playwright_images="$0 }' | tee "$GITHUB_OUTPUT"
      - name: PR playwright - comment
        uses: actions/github-script@v7
        if: github.event.pull_request.number != '' && hashFiles('./src/frontend/tests/playwright-report') != ''
        with:
          script: |
            const images_grid = '${{steps.pr_playwright-upload.outputs.pr_playwright_images}}'
              .split(',')
              .map(i => '<img src="' + i + '" width="400" />') // .replace("https://i.ibb.co/", "https://kbats.ru/imgbb/")
              .join(' ');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Playwright tests screens\n\n<p float="left">' + images_grid + '</p>'
            });

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./src/frontend/tests/playwright-report/
          retention-days: 3

      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: artifacts
            path: artifacts
            retention-days: 3
